#!/bin/bash

echo "🚀 FINAL DEPLOYMENT - Acadease Hackathon App"
echo "=============================================="

# Build the frontend
echo "📦 Building frontend for production..."
cd client
npm run build
cd ..

echo ""
echo "✅ BUILD COMPLETE!"
echo ""
echo "🌐 DEPLOYMENT OPTIONS:"
echo ""
echo "1. VERCEL (Recommended - Fastest):"
echo "   - Go to: https://vercel.com"
echo "   - Sign up with GitHub"
echo "   - Import this repository"
echo "   - Deploy automatically"
echo "   - Your app will be live at: https://your-app-name.vercel.app"
echo ""
echo "2. NETLIFY (Easy):"
echo "   - Go to: https://netlify.com"
echo "   - Drag and drop the 'client/dist' folder"
echo "   - Your app will be live instantly"
echo ""
echo "3. GITHUB PAGES:"
echo "   - Push to GitHub"
echo "   - Go to Settings > Pages"
echo "   - Select 'client/dist' as source"
echo "   - Your app will be live at: https://username.github.io/repo-name"
echo ""
echo "📁 READY TO DEPLOY:"
echo "   - Frontend files: client/dist/"
echo "   - Backend running: http://localhost:3003"
echo ""
echo "🔗 CURRENT LOCAL URLs:"
echo "   - Frontend: http://localhost:3001"
echo "   - Backend: http://localhost:3003"
echo ""
echo "🎯 FINAL HOSTED URL WILL BE:"
echo "   - Frontend: https://your-app-name.vercel.app"
echo "   - Backend: Deploy to Railway.app for https://your-backend.railway.app"
echo ""
echo "📋 QUICK DEPLOY STEPS:"
echo "1. Go to https://vercel.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New Project'"
echo "4. Import your repository"
echo "5. Deploy!"
echo ""
echo "🎉 Your hackathon app is ready for deployment!"

